# Generated by Django 5.0.6 on 2024-06-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mashauri", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatch",
            name="sla_timer",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dispatch",
            name="escalation_type",
            field=models.CharField(
                choices=[
                    ("Proactive", "Proactive"),
                    ("Reactive", "Reactive"),
                    ("OTB", "OTB"),
                    ("Support", "Support"),
                ],
                max_length=50,
            ),
        ),
    ]
