# Generated by Django 5.0.6 on 2024-06-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mashauri", "0002_dispatch_sla_timer_alter_dispatch_escalation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fdp_category",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Fireside", "Fireside"),
                    ("Broadcom", "Broadcom"),
                    ("Optimax", "Optimax"),
                    ("BTN", "BTN"),
                    ("Com21", "Com21"),
                ],
                default=None,
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="msp_category",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Egypro", "Egypro"),
                    ("Camusat", "Camusat"),
                    ("Adrian", "Adrian"),
                    ("Kinde", "Kinde"),
                    ("Fireside", "Fireside"),
                    ("Soliton", "Soliton"),
                ],
                default=None,
                max_length=50,
            ),
        ),
    ]
